### ISSUE TITLE
Uglifyfy creates many blank spaces

### ISSUE THREAD

**Issue by naorye** [hughsk/uglifyify#31]
Using uglifify with global:   
```b.transform(uglifyify, { global: true });```
   
I get many line spaces:
![screen shot 2015-01-28 at 1 14 30 am 1](https://cloud.githubusercontent.com/assets/2873571/5929266/ecdee8ac-a68a-11e4-9814-edac8b6dfeb9.png)

What is wrong?

**Comment by jamesreggio** [comment]
+1

This seems wrong.

**Comment by yoshuawuyts** [comment]
Hmh, that's odd. Does it cause any issues with source maps?

**Comment by naorye** [comment]
Not to me.

**Comment by TheLudd** [comment]
@yoshuawuyts I have noticed this as well, but only when I have source maps turned on. If I don't use source maps, the blank lines aren't there

**Comment by derekr** [comment]
Would it make sense to run a bundle that used `uglifyify` through `uglifyjs`?

**Comment by kristoferjoseph** [comment]
I'm seeing this as well.

**Comment by bholloway** [comment]
I believe this is caused by need for a [line break](https://github.com/hughsk/uglifyify/blob/master/index.js#L86) before the source map comment.

In browserify the source map for each file is encoded as a trailing source map comment. This allows it to be passed between transforms without any additional data structure. When the browser-pack occurs, the comment is stripped from the individual files in the pack but the comments are not.

Unfortunately this cannot be solved right now. Browserify and its dependencies need to upgrade to [convert-source-map@>=0.4.0](https://github.com/thlorenz/convert-source-map/releases/tag/v0.4.0) before the source map comment may be placed on the same line as the code.

This includes
* `insert-module-globals/combine-source-map/convert-source-map`
* `browser-pack/convert-source-map`.

**Comment by rahatarmanahmed** [comment]
What's the status of this issue? Both modules above are using a versino of `convert-source-map` above `0.4.0`.

**Comment by yoshuawuyts** [comment]
I'm not too fussed about this. From the docs:

> When using uglifyify you should generally also use Uglify, to achieve the smallest output

If this is not causing any source map issues then I'm not particularly seeing a problem here. However if anyone does however feel inclined to submit a patch, I'd be happy to review it. Cheers!
