### ISSUE TITLE
(v4) `ignore` is not a supported option

### ISSUE THREAD

**Issue by pixelass** [hughsk/uglifyify#73]
With the update to 4.0.2 (from 3.0.4) the ignore option stopped working.

```
errorify: `ignore` is not a supported option
```

It is still documented in the readme. I guess the switch to uglify-es caused this. I'm not sure how to ignore CSS files that are transpiled with css-modules

**Comment by pdparchitect** [comment]
uglifyify supports the ignore flag which is passed to minimatch. Unfortunately, the same options (used to setup uglifyify) are passed to uglify-es. Since the ignore option in uglifyify is not compatible with the options in uglify-es, you get this error.

The solution is to at the very least remove the ignore option from the options passed to uglify-es. Alternatively, if the user want to pass options directly to uglify-es, those can be defined in their own options, i.e. options.uglify.

At the moment the package is broken if you are to use the ignore flag.

Before the relevant pull requests are accepted, I suggest creating a post install script to patch the library.

**Comment by pixelass** [comment]
Moving away from Github. Feel free to reopen if interested.
